# Generated by Django 2.0.4 on 2018-06-04 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.CharField(max_length=30, verbose_name='文章ID')),
                ('article_name', models.CharField(max_length=50, unique=True, verbose_name='文章标题')),
                ('article_order', models.IntegerField(default=0, verbose_name='文章推广')),
                ('file', models.FileField(blank=True, null=True, upload_to='article/', verbose_name='附件')),
                ('article_body', models.TextField(verbose_name='文章内容')),
                ('article_status', models.TextField(choices=[('0', '新建'), ('1', '发布'), ('2', '撤回'), ('3', '审核')], default='0', verbose_name='文章状态')),
                ('article_starttime', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('article_updatetime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_comment_id', models.CharField(max_length=30, verbose_name='评论ID')),
                ('article_comment_body', models.TextField(verbose_name='评论内容')),
                ('article_comment_status', models.TextField(choices=[('0', '新建'), ('1', '发布'), ('2', '撤回'), ('3', '审核')], verbose_name='评论状态')),
                ('article_comment_starttime', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('article_comment_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articlecomment_for_article', to=settings.AUTH_USER_MODEL, verbose_name='文章关联')),
                ('article_comment_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articlecomment_for_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_type_name', models.CharField(max_length=30, verbose_name='文章分类')),
                ('article_type_body', models.TextField(verbose_name='分类简介')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articletype_type', to='ArticleManage.ArticleType', verbose_name='父菜单')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='article_type',
            field=models.ForeignKey(limit_choices_to={'parent__isnull': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articletype_for_article', to='ArticleManage.ArticleType', verbose_name='文章分类'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_for_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
