# Generated by Django 2.0.4 on 2018-06-04 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AssetManage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advance_vulns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('WEB', (('AWVS', 'AWVS'),)), ('System', (('Nessus', 'Nessus'),)), ('APP', (('MobSF', 'MobSF'),))], max_length=50, verbose_name='漏洞类型')),
                ('vuln_name', models.CharField(max_length=255, verbose_name='漏洞名称')),
                ('leave', models.CharField(choices=[('0', '信息'), ('1', '低危'), ('2', '中危'), ('3', '高危'), ('4', '紧急')], max_length=10, verbose_name='危险等级')),
                ('fix', models.TextField(null=True, verbose_name='修复方案')),
                ('create_data', models.DateTimeField(auto_now_add=True, verbose_name='发现时间')),
                ('update_data', models.DateTimeField(auto_now=True, verbose_name='修复时间')),
            ],
        ),
        migrations.CreateModel(
            name='Cnvdfiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='文件标题')),
                ('file', models.FileField(upload_to='cnvd/', verbose_name='CNVD文件')),
                ('update_data', models.DateField(auto_now=True, verbose_name='更新日期')),
            ],
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_id', models.CharField(max_length=30, verbose_name='漏洞编号')),
                ('cnvd_id', models.CharField(max_length=30, null=True, verbose_name='cnvd编号')),
                ('cve_name', models.CharField(max_length=255, verbose_name='漏洞名称')),
                ('leave', models.CharField(max_length=10, verbose_name='危险等级')),
                ('introduce', models.TextField(verbose_name='漏洞简介')),
                ('scopen', models.TextField(verbose_name='影响范围')),
                ('fix', models.TextField(verbose_name='修复方案')),
                ('fix_step', models.URLField(blank=True, null=True, verbose_name='修复指南')),
                ('update_data', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
        ),
        migrations.CreateModel(
            name='Vulnerability_scan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vuln_id', models.CharField(max_length=30, verbose_name='漏洞编号')),
                ('vuln_name', models.CharField(max_length=255, verbose_name='漏洞名称')),
                ('cve_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='cve编号')),
                ('vuln_type', models.CharField(max_length=60, verbose_name='漏洞属性')),
                ('leave', models.CharField(choices=[('0', '信息'), ('1', '低危'), ('2', '中危'), ('3', '高危'), ('4', '紧急')], max_length=10, verbose_name='危险等级')),
                ('introduce', models.TextField(null=True, verbose_name='漏洞简介')),
                ('vuln_info', models.TextField(null=True, verbose_name='漏洞信息')),
                ('scopen', models.TextField(verbose_name='影响范围')),
                ('fix', models.TextField(null=True, verbose_name='修复方案')),
                ('fix_action', models.TextField(null=True, verbose_name='处理记录')),
                ('fix_status', models.CharField(choices=[('0', '已忽略'), ('1', '已修复'), ('2', '待修复'), ('3', '漏洞重现'), ('4', '复查中')], max_length=30, verbose_name='修复状态')),
                ('create_data', models.DateTimeField(auto_now_add=True, verbose_name='发现时间')),
                ('update_data', models.DateTimeField(auto_now=True, verbose_name='修复时间')),
                ('vuln_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vuln_for_asset', to='AssetManage.Asset')),
            ],
        ),
    ]
