# Generated by Django 2.0.4 on 2018-06-04 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AssetManage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanner_name', models.CharField(max_length=50, verbose_name='节点名称')),
                ('scanner_type', models.CharField(choices=[('WEB', (('AWVS', 'AWVS'),)), ('System', (('Nessus', 'Nessus'),)), ('APP', (('MobSF', 'MobSF'),))], max_length=50, verbose_name='节点类型')),
                ('scanner_url', models.URLField(max_length=50, verbose_name='节点地址')),
                ('scanner_status', models.CharField(choices=[('启用', '启用'), ('禁用', '禁用')], default='禁用', max_length=50, verbose_name='节点状态')),
                ('scanner_apikey', models.CharField(max_length=100, verbose_name='API_KEY')),
                ('scanner_apisec', models.CharField(blank=True, max_length=100, verbose_name='API_SEC')),
                ('scanner_des', models.TextField(verbose_name='节点描述')),
                ('scanner_addtime', models.DateField(auto_now_add=True, verbose_name='开始时间')),
                ('scanner_updatetime', models.DateField(auto_now=True, verbose_name='结束时间')),
                ('assetType', models.ManyToManyField(limit_choices_to={'parent__isnull': False}, related_name='scanner_assettype', to='AssetManage.AssetType', verbose_name='扫描范围')),
            ],
        ),
        migrations.CreateModel(
            name='ScannerPolicies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policies_name', models.CharField(max_length=50, verbose_name='策略名称')),
                ('scanner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='police_for_scanner', to='SeMFSetting.Scanner', verbose_name='节点关联')),
            ],
        ),
    ]
